/**
 * types.ts
 *
 * TypeScript type definitions for the WS Financial Decision Engine frontend.
 *
 * These types mirror the data structures returned by the backend API
 * (POST /api/analyze) and used throughout the React components.
 */

// ─── PROFILE ──────────────────────────────────────────────────────────────────

/**
 * The user's financial profile — collected via the input form.
 * This is sent as-is to POST /api/analyze.
 */
export interface FinancialProfile {
  age:                  number;
  province:             string;   // ON | BC | AB | QC | MB
  annualIncome:         number;
  rrspBalance:          number;
  rrspRoom:             number;   // Unused contribution room (from CRA Notice of Assessment)
  tfsaBalance:          number;
  tfsaRoom:             number;   // Unused TFSA room (from CRA My Account)
  fhsaBalance:          number;   // 0 if no FHSA account
  nonRegisteredBalance: number;
  monthlySavings:       number;
  riskTolerance:        'conservative' | 'balanced' | 'growth' | 'aggressive';
  primaryGoal:          'retire' | 'buy_home' | 'fire' | 'wealth';
  timeHorizon:          number;   // Years until goal
  isFirstTimeBuyer:     boolean;
  rdspEnabled:          boolean;  // Optional: user has DTC eligibility
  rdspBalance:          number;   // Current RDSP balance
  rdspFamilyIncome:     number;   // Family net income (determines grant/bond rates)
}

// ─── SCENARIOS ────────────────────────────────────────────────────────────────

/**
 * Monte Carlo outcome percentiles for a single scenario at the end of the time horizon.
 * P10 = worst 10% of outcomes; P90 = best 10% of outcomes.
 */
export interface ScenarioProjection {
  p10: number;
  p25: number;
  p50: number;  // Median — the "most likely" outcome
  p75: number;
  p90: number;
}

/** Per-year percentile band, used to draw the projection chart. */
export interface YearBand {
  year: number;
  p10:  number;
  p50:  number;
  p90:  number;
}

/** Annual contribution breakdown across account types. */
export interface ContributionBreakdown {
  rrsp:           number;
  tfsa:           number;
  fhsa:           number;
  rdsp:           number;
  nonRegistered:  number;
}

/**
 * A single investment scenario — produced by the financial engine, then
 * enriched with AI narration from Claude.
 */
export interface Scenario {
  // ── Identification ──────────────────────────────────────────────────────────
  id:       string;  // e.g., 'rrsp_max', 'tfsa_max', 'balanced_split'
  name:     string;  // e.g., 'RRSP Maximizer'
  icon:     string;  // Emoji icon for the card
  tagline:  string;  // One-line hook

  // ── Strategy ────────────────────────────────────────────────────────────────
  description:     string;  // 2–3 sentence explanation of the strategy
  annual:          ContributionBreakdown;   // Annual contribution amounts per account
  monthly:         ContributionBreakdown;   // Same, divided by 12

  // ── Projections ─────────────────────────────────────────────────────────────
  projections:     ScenarioProjection;  // Final net worth outcomes (from Monte Carlo)
  byYear:          YearBand[];          // Year-by-year P10/P50/P90 for the chart

  // ── Tax ──────────────────────────────────────────────────────────────────────
  rrspTaxSaving:   number;  // Immediate tax refund from RRSP+FHSA contributions this year
  allocationLabel: string;  // e.g., 'Balanced (60/40)'

  // ── AI Narration (added by Claude) ──────────────────────────────────────────
  narration?: string;    // 2–3 sentence explanation personalised to this user
  pros?:      string[];  // 3 specific benefits
  cons?:      string[];  // 2 specific drawbacks
}

// ─── DECISION GATE ────────────────────────────────────────────────────────────

/**
 * A quantified risk relevant to the user's situation.
 * Generated by Claude's decision gate prompt.
 */
export interface Risk {
  name:        string;  // e.g., 'Interest Rate Risk'
  description: string;  // Specific, with numbers
  severity:    'high' | 'medium' | 'low';
  impact:      string;  // How this changes the recommendation
}

/**
 * The AI/human decision boundary output from Claude.
 * This is the core of the "human decision gate" concept:
 * the AI shows what it analyzed and what it can't know.
 */
export interface DecisionGate {
  recommendedScenarioId:   string;
  recommendedScenarioName: string;
  confidence:              'high' | 'medium' | 'low';
  confidenceReason:        string;
  aiAnalyzed:              string[];  // What the AI quantitatively analyzed
  humanMustDecide:         string[];  // What only the human can decide
  bottomLine:              string;    // One-paragraph honest summary
  risks:                   Risk[];
}

// ─── TAX SUMMARY ──────────────────────────────────────────────────────────────

export interface TaxSummary {
  totalTax:       number;
  effectiveRate:  number;  // e.g., 24.3 (percent, not decimal)
  marginalRate:   number;  // e.g., 43.4 (percent, not decimal)
  afterTaxIncome: number;
}

export interface ContributionRooms {
  rrsp:         number;
  tfsa:         number;
  fhsa:         number;
  fhsaEligible: boolean;
  rdsp:         number;
  rdspGrant:    number;
  rdspBond:     number;
  rdspEnabled:  boolean;
}

// ─── API RESPONSE ─────────────────────────────────────────────────────────────

/**
 * The full response from POST /api/analyze.
 * Stored in React state as `result` after a successful analysis.
 */
export interface AnalysisResult {
  scenarios:         Scenario[];
  taxSummary:        TaxSummary;
  contributionRooms: ContributionRooms;
  decisionGate:      DecisionGate;
}

// ─── UI STATE ─────────────────────────────────────────────────────────────────

/** The three views in the single-page app. */
export type AppView = 'profile' | 'analyzing' | 'results';
